name: Build Develop Ireland Mailroom
on:
  push:
    branches:
      - 'feature/build'
jobs:
  docker:
    runs-on: ubuntu-latest
    environment: 
      name: develop-ireland
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          ref:  feature/build
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Set output
        id: vars
        run: echo ::set-output name=tag::develop-v6.5.6
      - name: Login to ECR
        uses: docker/login-action@v1 
        with:
          registry: 452158872079.dkr.ecr.eu-west-1.amazonaws.com
          username: ${{ secrets.AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Build and push - Mailroom Image
        id: docker_build1
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/Dockerfile
          push: true
          tags: 452158872079.dkr.ecr.eu-west-1.amazonaws.com/mailroom:${{ steps.vars.outputs.tag }}
          no-cache: true